import mementoCover from './images/memento.jpg';
import americanPsychoCover from './images/americanPsycho.jpg';
import theWolfOfWallStreetCover from './images/theWolfOfWallStreet.jpg';
import inceptionCover from './images/inception.jpg';
import boratCover from './images/borat.jpg';
import thisIsSpinalTapCover from './images/thisIsSpinalTap.jpg';

export default function GetGallery() {
    return [
      {id: 'memento', title: 'Memento', image: mementoCover, synopsis: 'Memento chronicles two separate stories of Leonard, an ex-insurance investigator who can no longer build new memories, as he attempts to find the murderer of his wife, which is the last thing he remembers. One story line moves forward in time while the other tells the story backwards revealing more each time.'},
      {id: 'american-psycho', title: 'American Psycho', image: americanPsychoCover, synopsis: 'Patrick Bateman is handsome, well educated and intelligent. He is twenty-seven and living his own American dream. He works by day on Wall Street, earning a fortune to complement the one he was born with. At night he descends into madness, as he experiments with fear and violence.'},
      {id: 'the-wolf-of-wall-street', title: 'The Wolf of Wall Street', image: theWolfOfWallStreetCover, synopsis: 'Jordan Belfort is a Long Island penny stockbroker who served 22 months in prison for defrauding investors in a massive 1990s securities scam that involved widespread corruption on Wall Street and in the corporate banking world, including shoe designer Steve Madden.'},
      {id: 'inception', title: 'Inception', image: inceptionCover, synopsis: "Dom Cobb is a skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state, when the mind is at its most vulnerable. Cobb's rare ability has made him a coveted player in this treacherous new world of corporate espionage, but it has also made him an international fugitive and cost him everything he has ever loved. Now Cobb is being offered a chance at redemption. One last job could give him his life back but only if he can accomplish the impossible, inception. Instead of the perfect heist, Cobb and his team of specialists have to pull off the reverse: their task is not to steal an idea, but to plant one. If they succeed, it could be the perfect crime. But no amount of careful planning or expertise can prepare the team for the dangerous enemy that seems to predict their every move. An enemy that only Cobb could have seen coming."},
      {id: 'borat', title: 'Borat', image: boratCover, synopsis: "Borat Sagdiyev is a TV reporter of a popular show in Kazakhstan as Kazakhstan's sixth most famous man and a leading journalist. He is sent from his home to America by his government to make a documentary about American society and culture. Borat takes a course in New York City to understand American humor. While watching Baywatch on TV, Borat discovers how beautiful their women are in the form of C. J. Parker, who was played by actress Pamela Anderson who hails from Malibu, California. He decides to go on a cross-country road trip to California in a quest to make her his wife and take her back to his country. On his journey Borat and his producer encounter a country full of strange and wonderful Americans, real people in real chaotic situations with hysterical consequences."},
      {id: 'this-is-spinal-tap', title: 'This is Spinal Tap', image: thisIsSpinalTapCover, synopsis: "In 1982, the legendary English heavy metal band Spinal Tap attempt an American comeback tour accompanied by a fan who is also a film-maker. The resulting documentary, interspersed with powerful performances of Tap's pivotal music and profound lyrics, candidly follows a rock group heading towards crisis, culminating in the infamous affair of the eighteen-inch-high Stonehenge stage prop."}
    ];
  }